<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" scroll="no">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title id="page-title"><?= $this->portal ?> - <?= $this->login ?></title>
  <link rel="shortcut icon" href="/zf/public/images/favicon.ico" />
  <script type="text/javascript" src="/zf/public/js/jquery-1.10.1.min.js"></script>
  
  <?php if ($this->redirect) { ?>
  <script type="text/javascript" src="/zf/public/js/login.jsa?os_location=<?= $this->redirect ?>"></script>
  <?php } else { ?>
  <script type="text/javascript" src="/zf/public/js/login.jsa"></script>
  <?php } ?>

  <!-- 
  
  <?= $this->copyright ?>  
  
  -->
<style type="text/css">
#body{background-image:url(/zf/public/images/tausta.jpg);padding:2px;background-repeat:no-repeat;}

#ylla {width: 100%;background-color: #0F76BB;padding-bottom:60px;padding-top:20px;}

#mml {font: 24px arial black;color: #FFFFFF;margin-left: 20%;float:left;}

#certitudelogo {margin-right: 23%;float:right;}

#keskiboksi {background-color: hsla(240,100%,100%,0.50);margin-top:10%;margin-left:20%;margin-right:20%;padding-bottom:0px;padding-left:10px;border-radius: 6px;border: 1px solid #B6B6B6;float:left}

#mmllogo {margin-top:20px;padding-top:50px;padding-bottom:0px;float: left;}
	
#kirjautuminen {margin: 10px;margin-top:30px;font: 22px arial;color: #0F76BB;}

input[type=text] {width: 300px;height:30px;display: block;margin-bottom: 10px;border-radius: 5px;border: 1px solid #B6B6B6;float: left;font: 16px arial;color: #0F76BB;}

input[type=password] {width: 300px;height:30px;display: block;margin-bottom: 10px;border-radius: 5px;border: 1px solid #B6B6B6;float: left;font: 16px arial;color: #0F76BB;}
	
input[type=button] {width: 160px;height:35px;margin-bottom: 0px;border-radius: 5px;border: 1px #0F76BB;background-color:#0F76BB;font: 16px arial;color:#ffffff;}
input[type=button]:hover {width: 160px;height:35px;margin-bottom: 0px;border-radius: 5px;border: 1px #0F76BB;background-color:#3E6BD1;font: 16px arial;color:#ffffff;}

#tunnus {float: left;margin-left: 10px;color: #757579;margin-right: 10px;margin-bottom: 10px;font: 20px arial;}

#tunnus1 {float: left;margin-left: 10px;color: #757579;margin-right: 10px;margin-bottom: 10px;font: 20px arial;}

.form {padding-bottom: 20px;margin: 20px;margin-left:0px;float:left;margin-right:10px}

#oikeudet {height: 20px;width: 500px;bottom: 20px;right:150px;font: 12px arial;color: #0F76BB; position: relative; margin-right: 8%; margin-top:300px; margin-left:66%; float:left;}
</style>
</head>

<body id="body">
		<div id="ylla">
  			<div id="mml">JÄRKEVÄ-ERP</div>
  			<div id="certitudelogo"></div>
		</div>


		<div id="keskiboksi">
  			<div id="mmllogo"><img src="/zf/public/images/jarkeva-logo-musta.png" width="148" height="66" alt=""/></div>
    <div class="form">
			<div id="kirjautuminen"><?= $this->loginform ?></div>
      			
        			<form method="post" id="loginForm">
                      <div id="tunnus">
                        <p><?= $this->username ?>:</p> <input type="text" name="username" id="emailField" />
                      </div>
                      <div id="tunnus"><p><?= $this->password ?>: </p><input type="password" name="password" />
                      </div>
                      <div id="tunnus1">
                        <p></p></br><p></p><input type="button" id="submit" class="submit" value="Kirjaudu" name="submit"> <a href="/zf/public/default/index/lostpassword"><?= $this->lostpassword ?></a>
                      </div>
          
          			</form>
     
    
  				</div>
                
		</div>
		<div id="oikeudet"><?= $this->copyright ?></div>
        
</body>
</html>
